### ISSUE TITLE
Map refresh between two pages of pagination

### ISSUE THREAD

**Issue by vogloblinsky** [YoamFarges/LaBonneCarte#13]
For a search context, if i have 3 pages in the pagination, i need to click on "refresh" button each time i navigate to a new page.

**Comment by YoamFarges** [comment]
If you want to experiment with map automatically refreshing when content / page / tab changes, feel free to do so.

I tried a few solutions but decided after a while that the easiest way in terms of dev/maintenance effort would just to have a manual refresh.

**Comment by vogloblinsky** [comment]
Ok i understand your position
