### ISSUE TITLE
La carte ne s'affiche pas

### ISSUE THREAD

**Issue by JeremieMercier** [YoamFarges/LaBonneCarte#15]
Bonjour, La carte ne s'affiche pas, j'ai seulement le bouton mais quand je clique dessus aucune réaction.

Version de l'extension 3.0.2
Navigateur : Edge 93.0 et Chrome 93.0.

**Comment by YoamFarges** [comment]
Bonjour Jérémie,

Quel OS? Windows / Mac?
Avez-vous d'autres extensions installées? Si oui lesquelles?
Pouvez-vous me donner l'URL d'une page sur laquelle ca ne fonctionne pas?
Si c'est dans vos compétences, sauriez-vous voir si il n'y a pas de message
d'erreur dans la console chrome lorsque vous cliquez sur lebouton?

Merci d'avance,
Yoam


Le dim. 19 sept. 2021 à 14:40, Jérémie Mercier ***@***.***> a
écrit :

**Comment by YoamFarges** [comment]
No answer for 2 months. Closed.
