### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by jrmgx** [YoamFarges/LaBonneCarte#8]
Hello, I was just wondering if this project is still maintained?
The extension does not seem to work anymore.
Let me know

**Comment by YoamFarges** [comment]
Hello, it's not maintained as I don't have much time nowadays.
You are free to fork the project and try to make the parsing work again if you want to spend a fun weekend.

**Comment by jrmgx** [comment]
Thanks for the quick response. I’ll probably work on this at some point :)

**Comment by jrmgx** [comment]
Thank you for your code, it was quite easy to understand, well made, I've updated it here: https://github.com/jrmgx/LaBonneCarte (fix + added personal changes)
