### ISSUE TITLE
38 item parsed 7 geocoded

### ISSUE THREAD

**Issue by babarlelephant** [YoamFarges/LaBonneCarte#9]
Bonjour, merci pour ton travail,

Tu n'utilises pas le code postal ? (à la campagne c'est suffisant)

`[LaBonneCarte] Parse items : 38 items were found on the page.
chrome-extension://oegacpncaonolgbpmphcimodilfoacnl/utils/logger.js:2 [LaBonneCarte] Please wait for geocoding...
chrome-extension://oegacpncaonolgbpmphcimodilfoacnl/utils/logger.js:2 [LaBonneCarte] Geocoding done ! Will update the map with 7 geocoded items.
chrome-extension://oegacpncaonolgbpmphcimodilfoacnl/utils/logger.js:2 [LaBonneCarte] Map did finish marker update. You are ready to go! 👍`

**Comment by YoamFarges** [comment]
Hello,

Non j'utilise le code postal + le nom de la ville (https://github.com/YoamFarges/LaBonneCarte/blob/master/background/geocodeapi.js). Il n'est pas rare qu'un même code postal englobe plusieurs communes, même à la campagne, du coup... Pas vraiment le choix.
Par exemple vers là ou j'habite 01630 c'est 5 communes, non contigues, étalées sur 20km...

Pour la question du 38 items on page > 7 geocoded items, je n'ai pas le contexte mais :
1. Pas forcément une erreur si des items sur la page partagent le même code postal + nom de ville
2. Je n'ai pas maintenu l'extension depuis environ 1 an : il est possible que le changement de structure du bon coin ait des effets sur le parser.

A bientot,
Yoam

**Comment by acx01b** [comment]
OK en fait c'est une protection anti-DDOS qui fait que pas mal de tes requêtes à https://api-adresse.data.gouv.fr/search/?q=Castelnau-de-M%C3%A9doc&postcode=33480&limit=1 sont rejetées parce que tu les fais trop vite : https://www.chromium.org/throttling

En ajoutant 

`log(`Will retrieve "${location}" from data gouv api...`);
		
		var dt = new Date();  while ((new Date()) - dt <= 100) { }   // attendre 100 ms
		
        return await this.retrieveGeocodeFromDataGouv(cityName, postCode);`

ça marche

**Comment by acx01b** [comment]
Ensuite le prix ne s'affichait plus, pour que ça marche j'ai remplacé 

var price = node.querySelector('[itemprop="price"]');

par webpageparser.js

    var price = node.querySelector('span[itemprop="priceCurrency"]');

**Comment by acx01b** [comment]
Quand je fais une recherche la page 1 marche bien mais quand je vais sur la page 2 il y a un souci, le message 

    chrome.tabs.onUpdated.addListener(function (tabId, changeInfo, tab) {
        if (changeInfo.status == "loading" || extractRootDomain(tab.url) !== "leboncoin.fr") {
             return;
        }

est envoyé à un moment où 

               var nodes = this.document.querySelectorAll('[itemtype="http://schema.org/Offer"], [itemtype="http://schema.org/Demand"]');

ne contient que 3 éléments (les annonces mis en avant sur la droite). 

J'imagine que les 35 autres résultats sont récupérés en Ajax et qu'il faudrait donc rappeler

       parseItems()

 une dizaine fois toutes les secondes

**Comment by YoamFarges** [comment]
Merci beaucoup pour ton retour. N'hesites pas a faire une PR si jamais tu ameliores le code.

Pour info, voici ce que j'avais en tete l'an dernier pour continuer le projet (source: https://github.com/YoamFarges/LaBonneCarte/issues/6#issuecomment-508978989)
- Remove the map displaying automatically on top of the page
- Make the map only appear in a popup when you click manually click on the top-right extension icon
- Stop trying to figure out when a page refresh its information, and just parse the HTML snapshot of whenever the map is loaded.

A mon avis aujourd'hui ces points valent toujours. Si tu veux contribuer, je t'y encourage fortement.
Je mettrais a jour l'extension sur le Chrome Store si jamais nous arrivons a nouveau a quelque chose de stable.

**Comment by YoamFarges** [comment]
Closed issue after release 3.0.0 that should fix the issue by not relying on external geocoding websites.
